# services: mongodb
language: node_js
compiler: gcc
# env:
#   global:
#     - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - gcc-4.7
#       - g++-4.7
node_js:
  - "v9.6.1"
# before_install:
#   - "npm install -g webpack webpack-cli"
#   - "npm rebuild node-sass"
cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules